# Settings for the app
app:
  # HTML Title
  title: College Hill Corridor Idea Map
  # Header name
  name: College Hill Corridor Idea Map
  # Meta description that will show up in Google search results
  meta_description:  "Your Ideas to Improve the College Hill Corridor."

# Settings for map and layer configs
map:
  geolocation_enabled: true
  options:
    center:
      lat: 32.838
      lng: -83.6471455
    zoom: 15
    minZoom: 14
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-hv9oft1s/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  TrashRecycling:
    label: _(Trash/Recycling)
    default: puck-green
    focused: red
  PublicSafety:
    label: _(Public Safety)
    default: puck-blue
    focused: red
  Branding:
    default: puck-yellow
    focused: red
  Events:
    default: puck-red
    focused: red
  WalkingBiking:
    label: _(Walking/Biking)
    default: puck-purple
    focused: red
  Parks:
    default: puck-green
    focused: red
  Business:
    default: puck-blue
    focused: red
  Housing:
    default: puck-yellow
    focused: red
  Other:
    default: puck-red
    focused: red
  

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  puck-green:
    iconUrl: /static/css/images/markers/dot-70d52c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-blue:
    iconUrl: /static/css/images/markers/dot-2654d2.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-yellow:
    iconUrl: /static/css/images/markers/dot-dbcf2c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-red:
    iconUrl: /static/css/images/markers/dot-e1264d.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-purple:
    iconUrl: /static/css/images/markers/dot-744edc.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Share Your Idea
  title: Describe your idea...
  action_text: shared
  anonymous_name: Someone
  submit_button_label: Add to map
  items:
    - prompt: _(What's your idea?)
      type: select
      options:
        - label: _(Please choose...)
          value: TrashRecycling
        - label: _(Trash/Recycling)
          value: TrashRecycling
        - label: _(Public Safety)
          value: PublicSafety
        - label: _(Branding)
          value: Branding
        - label: _(Events)
          value: Events
        - label: _(Walking/Biking)
          value: WalkingBiking
        - label: _(Parks)
          value: Parks
        - label: _(Business)
          value: Business
        - label: _(Housing)
          value: Housing
        - label: _(Other)
          value: Other
      name: location_type            
    - prompt: _(Describe the location)
      type: text
      name: intersection_name
      optional: false
    - prompt: _(Tell us more about this idea)
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Share some more information.
    - prompt: Your Name
      type: text
      name: submitter_name
      attrs:
        - key: placeholder
          value: Your name will be visible on the map.
        - key: size
          value: 30
    - prompt: _(Your email (will not be visible on the map))
      type: text
      name: private-email
      attrs:
        - key: placeholder
          value: Your email will not be public.
        - key: size
          value: 30


survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Comment
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: 
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: placeholder
          value: 
        - key: size
          value: 30

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: More Info
    slug: about
    name: overview
    start_page: false
