# Settings for the app
app:
  # HTML Title
  title: Safer Salem
  # Header name
  name: Safe Routes to School & Play
  # Meta description that will show up in Google search results
  meta_description:  "Safe Routes to School & Play in Salem, MA."

# Settings for map and layer configs
map:
  geolocation_enabled: true
  options:
    center:
      lat: 42.51954
      lng: -70.8967155
    zoom: 16
    minZoom: 14
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-5f9w3eg9/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Autos:
    default: puck-green
    focused: dropper-green
    label: _(Auto Traffic issue)
  Pedestrians:
    default: puck-blue
    focused: dropper-blue
    label: _(Pedestrian Traffic issue)
  Bikes:
    default: puck-red
    focused: dropper-red
    label: _(Bike Traffic issue)
  PublicSpace:
    default: puck-yellow
    focused: dropper-yellow
    label: _(Public Space issue)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  puck-green:
    iconUrl: /static/css/images/markers/dot-70d52c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-blue:
    iconUrl: /static/css/images/markers/dot-2654d2.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-yellow:
    iconUrl: /static/css/images/markers/dot-dbcf2c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-red:
    iconUrl: /static/css/images/markers/dot-e1264d.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  puck-purple:
    iconUrl: /static/css/images/markers/dot-744edc.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  dropper-green:
    iconUrl: /static/css/images/markers/marker-70d52c.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  dropper-blue:
    iconUrl: /static/css/images/markers/marker-2654d2.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  dropper-yellow:
    iconUrl: /static/css/images/markers/marker-dbcf2c.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  dropper-red:
    iconUrl: /static/css/images/markers/marker-e1264d.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  dropper-purple:
    iconUrl: /static/css/images/markers/marker-744edc.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Identify a problem
  title: Tell us more...
  action_text: identified
  anonymous_name: Someone
  submit_button_label: Add to the map
  items:
    - prompt: ""
      type: select
      options:
        - label: _(Please choose a category)
          value: ""
        - label: _(Auto Traffic issues)
          value: "Autos"
        - label: _(Pedestrian Traffic issues)
          value: "Pedestrians"
        - label: _(Bike Traffic issues)
          value: "Bikes"
        - label: _(Public Space)
          value: "PublicSpace"          
      name: location_type

    # Pedestrian traffic checkboxes
    - prompt: Uneven or indirect path
      type: checkbox
      name: pedestrian1
      attrs:
        - key: value
          value: Uneven or indirect path
    - prompt: Sidewalk too narrow or missing
      type: checkbox
      name: pedestrian2
      attrs:
        - key: value
          value: Sidewalk too narrow or missing
    - prompt: Intersection or crossing issue
      type: checkbox
      name: pedestrian3
      attrs:
        - key: value
          value: Intersection or crossing issue
    - prompt: Other
      type: checkbox
      name: pedestrian4
      attrs:
        - key: value
          value: Other

    # traffic issues
    - prompt: Speeding
      type: checkbox
      name: traffic1
      attrs:
        - key: value
          value: Speeding
    - prompt: Confusing intersection
      type: checkbox
      name: traffic2
      attrs:
        - key: value
          value: Confusing intersection
    - prompt: Cut-through vehicles
      type: checkbox
      name: traffic3
      attrs:
        - key: value
          value: Cut-through vehicles
    - prompt: Other (please explain)
      type: checkbox
      name: traffic4
      attrs:
        - key: value
          value: Other (please explain)
    
    # bike issues
    - prompt: Obstacle or hazard in path
      type: checkbox
      name: bike1
      attrs:
        - key: value
          value: Obstacle or hazard in path
    - prompt: Bike infrastructure needed
      type: checkbox
      name: bike2
      attrs:
        - key: value
          value: Bike infrastructure needed
    - prompt: Bike parking needed
      type: checkbox
      name: bike3
      attrs:
        - key: value
          value: Bike parking needed
    - prompt: Other
      type: checkbox
      name: bike4
      attrs:
        - key: value
          value: Other

    # public space
    - prompt: Greenspace here please
      type: checkbox
      name: publicspace1
      attrs:
        - key: value
          value: Greenspace here please
    - prompt: Community garden here would be nice
      type: checkbox
      name: publicspace2
      attrs:
        - key: value
          value: Community garden here would be nice
    - prompt: More street trees
      type: checkbox
      name: publicspace3
      attrs:
        - key: value
          value: More street trees
    - prompt: Area does not feel safe or is unattractive
      type: checkbox
      name: publicspace4
      attrs:
        - key: value
          value: Area does not feel safe or is unattractive
    - prompt: Other
      type: checkbox
      name: publicspace5
      attrs:
        - key: value
          value: Other

    # other info
    - prompt: Share more details
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: Give us a brief description of the problem or place.      
    - prompt: _(Show us with a picture)
      inputfile_label: _(Upload an image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
    - prompt: Your name (optional, will be shown on the map)
      type: text
      name: submitter_name
      attrs:
        - key: size
          value: 30
    - prompt: Your email (will be kept private)
      type: text
      name: private-email
      attrs:
        - key: size
          value: 30
    - prompt: How do you typically get around for most trips? (will be kept private)
      type: text
      name: private-mode
      attrs:
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Description
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: ...
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: placeholder
          value: You must leave name to have your comment be visible to others.
        - key: size
          value: 30


support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: Welcome
    slug: welcome
    name: welcome
    start_page: true
  - title: About
    slug: about
    name: overview
    start_page: false